/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessTokenResponseDto
 */
export interface AccessTokenResponseDto {
    /**
     * JWT access token for authenticated requests
     * @type {string}
     * @memberof AccessTokenResponseDto
     */
    accessToken: string;
}

/**
 * Check if a given object implements the AccessTokenResponseDto interface.
 */
export function instanceOfAccessTokenResponseDto(value: object): value is AccessTokenResponseDto {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function AccessTokenResponseDtoFromJSON(json: any): AccessTokenResponseDto {
    return AccessTokenResponseDtoFromJSONTyped(json, false);
}

export function AccessTokenResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTokenResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
    };
}

export function AccessTokenResponseDtoToJSON(json: any): AccessTokenResponseDto {
    return AccessTokenResponseDtoToJSONTyped(json, false);
}

export function AccessTokenResponseDtoToJSONTyped(value?: AccessTokenResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
    };
}

