/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutSessionResponseDto
 */
export interface CheckoutSessionResponseDto {
    /**
     * Checkout session id generated by Stripe
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    sessionId: string;
    /**
     * Stripe-hosted URL where the user completes the subscription purchase
     * @type {string}
     * @memberof CheckoutSessionResponseDto
     */
    url: string;
}

/**
 * Check if a given object implements the CheckoutSessionResponseDto interface.
 */
export function instanceOfCheckoutSessionResponseDto(value: object): value is CheckoutSessionResponseDto {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CheckoutSessionResponseDtoFromJSON(json: any): CheckoutSessionResponseDto {
    return CheckoutSessionResponseDtoFromJSONTyped(json, false);
}

export function CheckoutSessionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'url': json['url'],
    };
}

export function CheckoutSessionResponseDtoToJSON(json: any): CheckoutSessionResponseDto {
    return CheckoutSessionResponseDtoToJSONTyped(json, false);
}

export function CheckoutSessionResponseDtoToJSONTyped(value?: CheckoutSessionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'url': value['url'],
    };
}

