/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCheckoutSessionDto
 */
export interface CreateCheckoutSessionDto {
    /**
     * Optional promotion code to apply immediately. If omitted, Stripe Checkout still allows entering a code manually.
     * @type {string}
     * @memberof CreateCheckoutSessionDto
     */
    couponCode?: string;
}

/**
 * Check if a given object implements the CreateCheckoutSessionDto interface.
 */
export function instanceOfCreateCheckoutSessionDto(value: object): value is CreateCheckoutSessionDto {
    return true;
}

export function CreateCheckoutSessionDtoFromJSON(json: any): CreateCheckoutSessionDto {
    return CreateCheckoutSessionDtoFromJSONTyped(json, false);
}

export function CreateCheckoutSessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCheckoutSessionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'couponCode': json['couponCode'] == null ? undefined : json['couponCode'],
    };
}

export function CreateCheckoutSessionDtoToJSON(json: any): CreateCheckoutSessionDto {
    return CreateCheckoutSessionDtoToJSONTyped(json, false);
}

export function CreateCheckoutSessionDtoToJSONTyped(value?: CreateCheckoutSessionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'couponCode': value['couponCode'],
    };
}

