/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookConfigDto } from './WebhookConfigDto';
import {
    WebhookConfigDtoFromJSON,
    WebhookConfigDtoFromJSONTyped,
    WebhookConfigDtoToJSON,
    WebhookConfigDtoToJSONTyped,
} from './WebhookConfigDto';

/**
 * 
 * @export
 * @interface CreateWaitListDto
 */
export interface CreateWaitListDto {
    /**
     * Name of the waitlist
     * @type {string}
     * @memberof CreateWaitListDto
     */
    name: string;
    /**
     * Whether to send confirmation email to new signups
     * @type {boolean}
     * @memberof CreateWaitListDto
     */
    sendEmailToNewSignup: boolean;
    /**
     * Webhook configuration for new signup notifications
     * @type {WebhookConfigDto}
     * @memberof CreateWaitListDto
     */
    webhook?: WebhookConfigDto;
    /**
     * Associated widget ID for embedding
     * @type {string}
     * @memberof CreateWaitListDto
     */
    widgetId?: string;
    /**
     * Whether the waitlist is accepting new signups
     * @type {boolean}
     * @memberof CreateWaitListDto
     */
    isAvailable?: boolean;
    /**
     * Whether the waitlist has security active
     * @type {boolean}
     * @memberof CreateWaitListDto
     */
    isSecurityActive?: boolean;
}

/**
 * Check if a given object implements the CreateWaitListDto interface.
 */
export function instanceOfCreateWaitListDto(value: object): value is CreateWaitListDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sendEmailToNewSignup' in value) || value['sendEmailToNewSignup'] === undefined) return false;
    return true;
}

export function CreateWaitListDtoFromJSON(json: any): CreateWaitListDto {
    return CreateWaitListDtoFromJSONTyped(json, false);
}

export function CreateWaitListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWaitListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'sendEmailToNewSignup': json['sendEmailToNewSignup'],
        'webhook': json['webhook'] == null ? undefined : WebhookConfigDtoFromJSON(json['webhook']),
        'widgetId': json['widget_id'] == null ? undefined : json['widget_id'],
        'isAvailable': json['isAvailable'] == null ? undefined : json['isAvailable'],
        'isSecurityActive': json['isSecurityActive'] == null ? undefined : json['isSecurityActive'],
    };
}

export function CreateWaitListDtoToJSON(json: any): CreateWaitListDto {
    return CreateWaitListDtoToJSONTyped(json, false);
}

export function CreateWaitListDtoToJSONTyped(value?: CreateWaitListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'sendEmailToNewSignup': value['sendEmailToNewSignup'],
        'webhook': WebhookConfigDtoToJSON(value['webhook']),
        'widget_id': value['widgetId'],
        'isAvailable': value['isAvailable'],
        'isSecurityActive': value['isSecurityActive'],
    };
}

