/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiKeyDto
 */
export interface CreateApiKeyDto {
    /**
     * Name to identify the API key
     * @type {string}
     * @memberof CreateApiKeyDto
     */
    name: string;
}

/**
 * Check if a given object implements the CreateApiKeyDto interface.
 */
export function instanceOfCreateApiKeyDto(value: object): value is CreateApiKeyDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateApiKeyDtoFromJSON(json: any): CreateApiKeyDto {
    return CreateApiKeyDtoFromJSONTyped(json, false);
}

export function CreateApiKeyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKeyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateApiKeyDtoToJSON(json: any): CreateApiKeyDto {
    return CreateApiKeyDtoToJSONTyped(json, false);
}

export function CreateApiKeyDtoToJSONTyped(value?: CreateApiKeyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

