/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutResponseDto
 */
export interface LogoutResponseDto {
    /**
     * Logout confirmation message
     * @type {string}
     * @memberof LogoutResponseDto
     */
    message: string;
}

/**
 * Check if a given object implements the LogoutResponseDto interface.
 */
export function instanceOfLogoutResponseDto(value: object): value is LogoutResponseDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LogoutResponseDtoFromJSON(json: any): LogoutResponseDto {
    return LogoutResponseDtoFromJSONTyped(json, false);
}

export function LogoutResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function LogoutResponseDtoToJSON(json: any): LogoutResponseDto {
    return LogoutResponseDtoToJSONTyped(json, false);
}

export function LogoutResponseDtoToJSONTyped(value?: LogoutResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

