/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReactToHtmlResponseDto
 */
export interface ReactToHtmlResponseDto {
    /**
     * Compiled HTML output from React component
     * @type {string}
     * @memberof ReactToHtmlResponseDto
     */
    html: string;
}

/**
 * Check if a given object implements the ReactToHtmlResponseDto interface.
 */
export function instanceOfReactToHtmlResponseDto(value: object): value is ReactToHtmlResponseDto {
    if (!('html' in value) || value['html'] === undefined) return false;
    return true;
}

export function ReactToHtmlResponseDtoFromJSON(json: any): ReactToHtmlResponseDto {
    return ReactToHtmlResponseDtoFromJSONTyped(json, false);
}

export function ReactToHtmlResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReactToHtmlResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'html': json['html'],
    };
}

export function ReactToHtmlResponseDtoToJSON(json: any): ReactToHtmlResponseDto {
    return ReactToHtmlResponseDtoToJSONTyped(json, false);
}

export function ReactToHtmlResponseDtoToJSONTyped(value?: ReactToHtmlResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html': value['html'],
    };
}

