/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReactToHtmlDto
 */
export interface ReactToHtmlDto {
    /**
     * React component code to be compiled to HTML
     * @type {string}
     * @memberof ReactToHtmlDto
     */
    code: string;
}

/**
 * Check if a given object implements the ReactToHtmlDto interface.
 */
export function instanceOfReactToHtmlDto(value: object): value is ReactToHtmlDto {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ReactToHtmlDtoFromJSON(json: any): ReactToHtmlDto {
    return ReactToHtmlDtoFromJSONTyped(json, false);
}

export function ReactToHtmlDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReactToHtmlDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function ReactToHtmlDtoToJSON(json: any): ReactToHtmlDto {
    return ReactToHtmlDtoToJSONTyped(json, false);
}

export function ReactToHtmlDtoToJSONTyped(value?: ReactToHtmlDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

