/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterWaitListUserDto
 */
export interface RegisterWaitListUserDto {
    /**
     * Email address of the user joining the waitlist
     * @type {string}
     * @memberof RegisterWaitListUserDto
     */
    email: string;
    /**
     * Referral code from another user who referred this signup
     * @type {string}
     * @memberof RegisterWaitListUserDto
     */
    referredBy?: string;
}

/**
 * Check if a given object implements the RegisterWaitListUserDto interface.
 */
export function instanceOfRegisterWaitListUserDto(value: object): value is RegisterWaitListUserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RegisterWaitListUserDtoFromJSON(json: any): RegisterWaitListUserDto {
    return RegisterWaitListUserDtoFromJSONTyped(json, false);
}

export function RegisterWaitListUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterWaitListUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'referredBy': json['referredBy'] == null ? undefined : json['referredBy'],
    };
}

export function RegisterWaitListUserDtoToJSON(json: any): RegisterWaitListUserDto {
    return RegisterWaitListUserDtoToJSONTyped(json, false);
}

export function RegisterWaitListUserDtoToJSONTyped(value?: RegisterWaitListUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'referredBy': value['referredBy'],
    };
}

