/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApiKeyDto
 */
export interface UpdateApiKeyDto {
    /**
     * Name to identify the API key
     * @type {string}
     * @memberof UpdateApiKeyDto
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateApiKeyDto interface.
 */
export function instanceOfUpdateApiKeyDto(value: object): value is UpdateApiKeyDto {
    return true;
}

export function UpdateApiKeyDtoFromJSON(json: any): UpdateApiKeyDto {
    return UpdateApiKeyDtoFromJSONTyped(json, false);
}

export function UpdateApiKeyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApiKeyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateApiKeyDtoToJSON(json: any): UpdateApiKeyDto {
    return UpdateApiKeyDtoToJSONTyped(json, false);
}

export function UpdateApiKeyDtoToJSONTyped(value?: UpdateApiKeyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

