/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookConfigDto } from './WebhookConfigDto';
import {
    WebhookConfigDtoFromJSON,
    WebhookConfigDtoFromJSONTyped,
    WebhookConfigDtoToJSON,
    WebhookConfigDtoToJSONTyped,
} from './WebhookConfigDto';

/**
 * 
 * @export
 * @interface UpdateWaitListDto
 */
export interface UpdateWaitListDto {
    /**
     * Name of the waitlist
     * @type {string}
     * @memberof UpdateWaitListDto
     */
    name?: string;
    /**
     * Whether to send confirmation email to new signups
     * @type {boolean}
     * @memberof UpdateWaitListDto
     */
    sendEmailToNewSignup?: boolean;
    /**
     * Webhook configuration for new signup notifications
     * @type {WebhookConfigDto}
     * @memberof UpdateWaitListDto
     */
    webhook?: WebhookConfigDto;
    /**
     * Associated widget ID for embedding
     * @type {string}
     * @memberof UpdateWaitListDto
     */
    widgetId?: string;
    /**
     * Whether the waitlist is accepting new signups
     * @type {boolean}
     * @memberof UpdateWaitListDto
     */
    isAvailable?: boolean;
    /**
     * Whether the waitlist has security active
     * @type {boolean}
     * @memberof UpdateWaitListDto
     */
    isSecurityActive?: boolean;
}

/**
 * Check if a given object implements the UpdateWaitListDto interface.
 */
export function instanceOfUpdateWaitListDto(value: object): value is UpdateWaitListDto {
    return true;
}

export function UpdateWaitListDtoFromJSON(json: any): UpdateWaitListDto {
    return UpdateWaitListDtoFromJSONTyped(json, false);
}

export function UpdateWaitListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWaitListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'sendEmailToNewSignup': json['sendEmailToNewSignup'] == null ? undefined : json['sendEmailToNewSignup'],
        'webhook': json['webhook'] == null ? undefined : WebhookConfigDtoFromJSON(json['webhook']),
        'widgetId': json['widget_id'] == null ? undefined : json['widget_id'],
        'isAvailable': json['isAvailable'] == null ? undefined : json['isAvailable'],
        'isSecurityActive': json['isSecurityActive'] == null ? undefined : json['isSecurityActive'],
    };
}

export function UpdateWaitListDtoToJSON(json: any): UpdateWaitListDto {
    return UpdateWaitListDtoToJSONTyped(json, false);
}

export function UpdateWaitListDtoToJSONTyped(value?: UpdateWaitListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'sendEmailToNewSignup': value['sendEmailToNewSignup'],
        'webhook': WebhookConfigDtoToJSON(value['webhook']),
        'widget_id': value['widgetId'],
        'isAvailable': value['isAvailable'],
        'isSecurityActive': value['isSecurityActive'],
    };
}

