/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileResponseDto
 */
export interface UserProfileResponseDto {
    /**
     * User unique identifier
     * @type {string}
     * @memberof UserProfileResponseDto
     */
    userId: string;
}

/**
 * Check if a given object implements the UserProfileResponseDto interface.
 */
export function instanceOfUserProfileResponseDto(value: object): value is UserProfileResponseDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UserProfileResponseDtoFromJSON(json: any): UserProfileResponseDto {
    return UserProfileResponseDtoFromJSONTyped(json, false);
}

export function UserProfileResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function UserProfileResponseDtoToJSON(json: any): UserProfileResponseDto {
    return UserProfileResponseDtoToJSONTyped(json, false);
}

export function UserProfileResponseDtoToJSONTyped(value?: UserProfileResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

