/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WaitListUserCountResponseDto
 */
export interface WaitListUserCountResponseDto {
    /**
     * Total number of users in the waitlist
     * @type {number}
     * @memberof WaitListUserCountResponseDto
     */
    total: number;
    /**
     * Number of users who signed up via referral
     * @type {number}
     * @memberof WaitListUserCountResponseDto
     */
    referred: number;
}

/**
 * Check if a given object implements the WaitListUserCountResponseDto interface.
 */
export function instanceOfWaitListUserCountResponseDto(value: object): value is WaitListUserCountResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('referred' in value) || value['referred'] === undefined) return false;
    return true;
}

export function WaitListUserCountResponseDtoFromJSON(json: any): WaitListUserCountResponseDto {
    return WaitListUserCountResponseDtoFromJSONTyped(json, false);
}

export function WaitListUserCountResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitListUserCountResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'referred': json['referred'],
    };
}

export function WaitListUserCountResponseDtoToJSON(json: any): WaitListUserCountResponseDto {
    return WaitListUserCountResponseDtoToJSONTyped(json, false);
}

export function WaitListUserCountResponseDtoToJSONTyped(value?: WaitListUserCountResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'referred': value['referred'],
    };
}

