/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WaitListUserResponseDto
 */
export interface WaitListUserResponseDto {
    /**
     * Unique identifier of the waitlist user entry
     * @type {string}
     * @memberof WaitListUserResponseDto
     */
    id: string;
    /**
     * Email address of the registered user
     * @type {string}
     * @memberof WaitListUserResponseDto
     */
    email: string;
    /**
     * Waitlist ID this user belongs to
     * @type {string}
     * @memberof WaitListUserResponseDto
     */
    waitlistId: string;
    /**
     * Referral code of the user who referred this signup
     * @type {string}
     * @memberof WaitListUserResponseDto
     */
    referredBy?: string;
    /**
     * Unique referral code for this user to share
     * @type {string}
     * @memberof WaitListUserResponseDto
     */
    referralCode: string;
    /**
     * Registration timestamp
     * @type {Date}
     * @memberof WaitListUserResponseDto
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the WaitListUserResponseDto interface.
 */
export function instanceOfWaitListUserResponseDto(value: object): value is WaitListUserResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('waitlistId' in value) || value['waitlistId'] === undefined) return false;
    if (!('referralCode' in value) || value['referralCode'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function WaitListUserResponseDtoFromJSON(json: any): WaitListUserResponseDto {
    return WaitListUserResponseDtoFromJSONTyped(json, false);
}

export function WaitListUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitListUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'email': json['email'],
        'waitlistId': json['waitlistId'],
        'referredBy': json['referredBy'] == null ? undefined : json['referredBy'],
        'referralCode': json['referral_code'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function WaitListUserResponseDtoToJSON(json: any): WaitListUserResponseDto {
    return WaitListUserResponseDtoToJSONTyped(json, false);
}

export function WaitListUserResponseDtoToJSONTyped(value?: WaitListUserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'email': value['email'],
        'waitlistId': value['waitlistId'],
        'referredBy': value['referredBy'],
        'referral_code': value['referralCode'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

