/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WaitListResponseDto
 */
export interface WaitListResponseDto {
    /**
     * Unique identifier of the waitlist
     * @type {string}
     * @memberof WaitListResponseDto
     */
    id: string;
    /**
     * Name of the waitlist
     * @type {string}
     * @memberof WaitListResponseDto
     */
    name: string;
    /**
     * Whether confirmation emails are sent to new signups
     * @type {boolean}
     * @memberof WaitListResponseDto
     */
    sendEmailToNewSignup: boolean;
    /**
     * Webhook URL for new signup notifications
     * @type {object}
     * @memberof WaitListResponseDto
     */
    webhook?: object;
    /**
     * Associated widget ID
     * @type {string}
     * @memberof WaitListResponseDto
     */
    widgetId?: string;
    /**
     * Whether the waitlist is accepting signups
     * @type {boolean}
     * @memberof WaitListResponseDto
     */
    isAvailable: boolean;
    /**
     * Owner user ID
     * @type {string}
     * @memberof WaitListResponseDto
     */
    userId: string;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof WaitListResponseDto
     */
    createdAt: Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof WaitListResponseDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the WaitListResponseDto interface.
 */
export function instanceOfWaitListResponseDto(value: object): value is WaitListResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sendEmailToNewSignup' in value) || value['sendEmailToNewSignup'] === undefined) return false;
    if (!('isAvailable' in value) || value['isAvailable'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WaitListResponseDtoFromJSON(json: any): WaitListResponseDto {
    return WaitListResponseDtoFromJSONTyped(json, false);
}

export function WaitListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'name': json['name'],
        'sendEmailToNewSignup': json['sendEmailToNewSignup'],
        'webhook': json['webhook'] == null ? undefined : json['webhook'],
        'widgetId': json['widget_id'] == null ? undefined : json['widget_id'],
        'isAvailable': json['isAvailable'],
        'userId': json['user_id'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function WaitListResponseDtoToJSON(json: any): WaitListResponseDto {
    return WaitListResponseDtoToJSONTyped(json, false);
}

export function WaitListResponseDtoToJSONTyped(value?: WaitListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'name': value['name'],
        'sendEmailToNewSignup': value['sendEmailToNewSignup'],
        'webhook': value['webhook'],
        'widget_id': value['widgetId'],
        'isAvailable': value['isAvailable'],
        'user_id': value['userId'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

