/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookAcceptedResponseDto
 */
export interface WebhookAcceptedResponseDto {
    /**
     * Indicates that webhook event was accepted
     * @type {boolean}
     * @memberof WebhookAcceptedResponseDto
     */
    received: boolean;
}

/**
 * Check if a given object implements the WebhookAcceptedResponseDto interface.
 */
export function instanceOfWebhookAcceptedResponseDto(value: object): value is WebhookAcceptedResponseDto {
    if (!('received' in value) || value['received'] === undefined) return false;
    return true;
}

export function WebhookAcceptedResponseDtoFromJSON(json: any): WebhookAcceptedResponseDto {
    return WebhookAcceptedResponseDtoFromJSONTyped(json, false);
}

export function WebhookAcceptedResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookAcceptedResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'received': json['received'],
    };
}

export function WebhookAcceptedResponseDtoToJSON(json: any): WebhookAcceptedResponseDto {
    return WebhookAcceptedResponseDtoToJSONTyped(json, false);
}

export function WebhookAcceptedResponseDtoToJSONTyped(value?: WebhookAcceptedResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'received': value['received'],
    };
}

