/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookConfigDto
 */
export interface WebhookConfigDto {
    /**
     * Webhook URL to notify when a new user signs up
     * @type {string}
     * @memberof WebhookConfigDto
     */
    url?: string;
    /**
     * Notify webhook every N users registered
     * @type {number}
     * @memberof WebhookConfigDto
     */
    range?: number;
}

/**
 * Check if a given object implements the WebhookConfigDto interface.
 */
export function instanceOfWebhookConfigDto(value: object): value is WebhookConfigDto {
    return true;
}

export function WebhookConfigDtoFromJSON(json: any): WebhookConfigDto {
    return WebhookConfigDtoFromJSONTyped(json, false);
}

export function WebhookConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookConfigDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'range': json['range'] == null ? undefined : json['range'],
    };
}

export function WebhookConfigDtoToJSON(json: any): WebhookConfigDto {
    return WebhookConfigDtoToJSONTyped(json, false);
}

export function WebhookConfigDtoToJSONTyped(value?: WebhookConfigDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'range': value['range'],
    };
}

