/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateApiKeyDto,
  UpdateApiKeyDto,
} from '../models/index';
import {
    CreateApiKeyDtoFromJSON,
    CreateApiKeyDtoToJSON,
    UpdateApiKeyDtoFromJSON,
    UpdateApiKeyDtoToJSON,
} from '../models/index';

export interface APIKeysCreateRequest {
    createApiKeyDto: CreateApiKeyDto;
}

export interface APIKeysFindOneRequest {
    id: object;
}

export interface APIKeysRemoveRequest {
    id: object;
}

export interface APIKeysUpdateRequest {
    id: object;
    updateApiKeyDto: UpdateApiKeyDto;
}

/**
 * 
 */
export class APIKeysApi extends runtime.BaseAPI {

    /**
     * Creates request options for aPIKeysCreate without sending the request
     */
    async aPIKeysCreateRequestOpts(requestParameters: APIKeysCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createApiKeyDto'] == null) {
            throw new runtime.RequiredError(
                'createApiKeyDto',
                'Required parameter "createApiKeyDto" was null or undefined when calling aPIKeysCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-key`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateApiKeyDtoToJSON(requestParameters['createApiKeyDto']),
        };
    }

    /**
     * Creates a new API key for the authenticated user.
     * Create a new API key
     */
    async aPIKeysCreateRaw(requestParameters: APIKeysCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.aPIKeysCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new API key for the authenticated user.
     * Create a new API key
     */
    async aPIKeysCreate(requestParameters: APIKeysCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.aPIKeysCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for aPIKeysFindAll without sending the request
     */
    async aPIKeysFindAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-key`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves all API keys owned by the authenticated user.
     * Get all API keys
     */
    async aPIKeysFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.aPIKeysFindAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves all API keys owned by the authenticated user.
     * Get all API keys
     */
    async aPIKeysFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.aPIKeysFindAllRaw(initOverrides);
    }

    /**
     * Creates request options for aPIKeysFindOne without sending the request
     */
    async aPIKeysFindOneRequestOpts(requestParameters: APIKeysFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling aPIKeysFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-key/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a specific API key by ID.
     * Get a specific API key
     */
    async aPIKeysFindOneRaw(requestParameters: APIKeysFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.aPIKeysFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves a specific API key by ID.
     * Get a specific API key
     */
    async aPIKeysFindOne(requestParameters: APIKeysFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.aPIKeysFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for aPIKeysRemove without sending the request
     */
    async aPIKeysRemoveRequestOpts(requestParameters: APIKeysRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling aPIKeysRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-key/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permanently deletes an API key. This action cannot be undone.
     * Delete an API key
     */
    async aPIKeysRemoveRaw(requestParameters: APIKeysRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.aPIKeysRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes an API key. This action cannot be undone.
     * Delete an API key
     */
    async aPIKeysRemove(requestParameters: APIKeysRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.aPIKeysRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for aPIKeysUpdate without sending the request
     */
    async aPIKeysUpdateRequestOpts(requestParameters: APIKeysUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling aPIKeysUpdate().'
            );
        }

        if (requestParameters['updateApiKeyDto'] == null) {
            throw new runtime.RequiredError(
                'updateApiKeyDto',
                'Required parameter "updateApiKeyDto" was null or undefined when calling aPIKeysUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-key/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateApiKeyDtoToJSON(requestParameters['updateApiKeyDto']),
        };
    }

    /**
     * Updates an existing API key. Only the owner can update.
     * Update an API key
     */
    async aPIKeysUpdateRaw(requestParameters: APIKeysUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.aPIKeysUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates an existing API key. Only the owner can update.
     * Update an API key
     */
    async aPIKeysUpdate(requestParameters: APIKeysUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.aPIKeysUpdateRaw(requestParameters, initOverrides);
    }

}
