/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccessTokenResponseDto,
  CreateUserDto,
  LoginDto,
  LogoutResponseDto,
  UserProfileResponseDto,
} from '../models/index';
import {
    AccessTokenResponseDtoFromJSON,
    AccessTokenResponseDtoToJSON,
    CreateUserDtoFromJSON,
    CreateUserDtoToJSON,
    LoginDtoFromJSON,
    LoginDtoToJSON,
    LogoutResponseDtoFromJSON,
    LogoutResponseDtoToJSON,
    UserProfileResponseDtoFromJSON,
    UserProfileResponseDtoToJSON,
} from '../models/index';

export interface AuthRegisterRequest {
    createUserDto: CreateUserDto;
}

export interface LoginRequest {
    loginDto: LoginDto;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authRegister without sending the request
     */
    async authRegisterRequestOpts(requestParameters: AuthRegisterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createUserDto'] == null) {
            throw new runtime.RequiredError(
                'createUserDto',
                'Required parameter "createUserDto" was null or undefined when calling authRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserDtoToJSON(requestParameters['createUserDto']),
        };
    }

    /**
     * Create a new user account. Returns JWT access token upon successful registration.
     * User registration
     */
    async authRegisterRaw(requestParameters: AuthRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessTokenResponseDto>> {
        const requestOptions = await this.authRegisterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a new user account. Returns JWT access token upon successful registration.
     * User registration
     */
    async authRegister(requestParameters: AuthRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessTokenResponseDto> {
        const response = await this.authRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProfile without sending the request
     */
    async getProfileRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/profile`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the authenticated user profile information.
     * Get current user profile
     */
    async getProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserProfileResponseDto>> {
        const requestOptions = await this.getProfileRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserProfileResponseDtoFromJSON(jsonValue));
    }

    /**
     * Returns the authenticated user profile information.
     * Get current user profile
     */
    async getProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserProfileResponseDto> {
        const response = await this.getProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for github without sending the request
     */
    async githubRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/github`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Initiates GitHub OAuth2 authentication flow. Redirects to GitHub login page.
     * GitHub OAuth login
     */
    async githubRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.githubRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Initiates GitHub OAuth2 authentication flow. Redirects to GitHub login page.
     * GitHub OAuth login
     */
    async github(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.githubRaw(initOverrides);
    }

    /**
     * Creates request options for githubAuthRedirect without sending the request
     */
    async githubAuthRedirectRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/github/callback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Handles GitHub OAuth2 callback. Sets cookie and redirects to frontend.
     * GitHub OAuth callback
     */
    async githubAuthRedirectRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.githubAuthRedirectRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handles GitHub OAuth2 callback. Sets cookie and redirects to frontend.
     * GitHub OAuth callback
     */
    async githubAuthRedirect(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.githubAuthRedirectRaw(initOverrides);
    }

    /**
     * Creates request options for google without sending the request
     */
    async googleRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/google`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Initiates Google OAuth2 authentication flow. Redirects to Google login page.
     * Google OAuth login
     */
    async googleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.googleRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Initiates Google OAuth2 authentication flow. Redirects to Google login page.
     * Google OAuth login
     */
    async google(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.googleRaw(initOverrides);
    }

    /**
     * Creates request options for googleAuthRedirect without sending the request
     */
    async googleAuthRedirectRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/google/callback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Handles Google OAuth2 callback. Sets cookie and redirects to frontend.
     * Google OAuth callback
     */
    async googleAuthRedirectRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.googleAuthRedirectRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handles Google OAuth2 callback. Sets cookie and redirects to frontend.
     * Google OAuth callback
     */
    async googleAuthRedirect(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.googleAuthRedirectRaw(initOverrides);
    }

    /**
     * Creates request options for login without sending the request
     */
    async loginRequestOpts(requestParameters: LoginRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['loginDto'] == null) {
            throw new runtime.RequiredError(
                'loginDto',
                'Required parameter "loginDto" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginDtoToJSON(requestParameters['loginDto']),
        };
    }

    /**
     * Authenticate user with email and password. Returns JWT access token.
     * User login
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessTokenResponseDto>> {
        const requestOptions = await this.loginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessTokenResponseDtoFromJSON(jsonValue));
    }

    /**
     * Authenticate user with email and password. Returns JWT access token.
     * User login
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessTokenResponseDto> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for logout without sending the request
     */
    async logoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/auth/logout`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Clears authentication cookies and logs out the user.
     * User logout
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LogoutResponseDto>> {
        const requestOptions = await this.logoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LogoutResponseDtoFromJSON(jsonValue));
    }

    /**
     * Clears authentication cookies and logs out the user.
     * User logout
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LogoutResponseDto> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profile without sending the request
     */
    async profileRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/refresh-token`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async profileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.profileRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async profile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.profileRaw(initOverrides);
    }

}
