/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReactToHtmlDto,
  ReactToHtmlResponseDto,
} from '../models/index';
import {
    ReactToHtmlDtoFromJSON,
    ReactToHtmlDtoToJSON,
    ReactToHtmlResponseDtoFromJSON,
    ReactToHtmlResponseDtoToJSON,
} from '../models/index';

export interface CompileRequest {
    reactToHtmlDto: ReactToHtmlDto;
}

/**
 * 
 */
export class ReactToHTMLApi extends runtime.BaseAPI {

    /**
     * Creates request options for compile without sending the request
     */
    async compileRequestOpts(requestParameters: CompileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reactToHtmlDto'] == null) {
            throw new runtime.RequiredError(
                'reactToHtmlDto',
                'Required parameter "reactToHtmlDto" was null or undefined when calling compile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/react2html`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReactToHtmlDtoToJSON(requestParameters['reactToHtmlDto']),
        };
    }

    /**
     * Compiles React email components to static HTML.       This endpoint is useful for generating email templates using React Email components. The input should be valid React/JSX code that exports a default component.  **Supported packages:** - @react-email/components (Html, Head, Body, Container, Text, Button, etc.)
     * Compile React to HTML
     */
    async compileRaw(requestParameters: CompileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReactToHtmlResponseDto>> {
        const requestOptions = await this.compileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReactToHtmlResponseDtoFromJSON(jsonValue));
    }

    /**
     * Compiles React email components to static HTML.       This endpoint is useful for generating email templates using React Email components. The input should be valid React/JSX code that exports a default component.  **Supported packages:** - @react-email/components (Html, Head, Body, Container, Text, Button, etc.)
     * Compile React to HTML
     */
    async compile(requestParameters: CompileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReactToHtmlResponseDto> {
        const response = await this.compileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
