/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CheckoutSessionResponseDto,
  CreateCheckoutSessionDto,
  WebhookAcceptedResponseDto,
} from '../models/index';
import {
    CheckoutSessionResponseDtoFromJSON,
    CheckoutSessionResponseDtoToJSON,
    CreateCheckoutSessionDtoFromJSON,
    CreateCheckoutSessionDtoToJSON,
    WebhookAcceptedResponseDtoFromJSON,
    WebhookAcceptedResponseDtoToJSON,
} from '../models/index';

export interface CreateCheckoutSessionRequest {
    createCheckoutSessionDto?: CreateCheckoutSessionDto;
}

/**
 * 
 */
export class SubscriptionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCheckoutSession without sending the request
     */
    async createCheckoutSessionRequestOpts(requestParameters: CreateCheckoutSessionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/subscriptions/checkout-session`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCheckoutSessionDtoToJSON(requestParameters['createCheckoutSessionDto']),
        };
    }

    /**
     * Creates a Stripe-hosted checkout session for the current user subscription.
     * Create Stripe checkout session for Zot Premium
     */
    async createCheckoutSessionRaw(requestParameters: CreateCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutSessionResponseDto>> {
        const requestOptions = await this.createCheckoutSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutSessionResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates a Stripe-hosted checkout session for the current user subscription.
     * Create Stripe checkout session for Zot Premium
     */
    async createCheckoutSession(requestParameters: CreateCheckoutSessionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutSessionResponseDto> {
        const response = await this.createCheckoutSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stripeWebhook without sending the request
     */
    async stripeWebhookRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/subscriptions/webhook`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Receives Stripe events and keeps user plan and quotes synchronized.
     * Stripe webhook receiver
     */
    async stripeWebhookRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookAcceptedResponseDto>> {
        const requestOptions = await this.stripeWebhookRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookAcceptedResponseDtoFromJSON(jsonValue));
    }

    /**
     * Receives Stripe events and keeps user plan and quotes synchronized.
     * Stripe webhook receiver
     */
    async stripeWebhook(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookAcceptedResponseDto> {
        const response = await this.stripeWebhookRaw(initOverrides);
        return await response.value();
    }

}
