/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RegisterWaitListUserDto,
  WaitListUserCountResponseDto,
  WaitListUserResponseDto,
} from '../models/index';
import {
    RegisterWaitListUserDtoFromJSON,
    RegisterWaitListUserDtoToJSON,
    WaitListUserCountResponseDtoFromJSON,
    WaitListUserCountResponseDtoToJSON,
    WaitListUserResponseDtoFromJSON,
    WaitListUserResponseDtoToJSON,
} from '../models/index';

export interface CountRequest {
    waitlistId: object;
}

export interface FindByEmailRequest {
    waitlistId: object;
    email: string;
}

export interface WaitListUsersFindAllRequest {
    waitlistId: object;
}

export interface WaitListUsersRegisterRequest {
    waitlistId: object;
    registerWaitListUserDto: RegisterWaitListUserDto;
}

export interface WaitListUsersRemoveRequest {
    waitlistId: object;
    email: string;
}

/**
 * 
 */
export class WaitListUsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for count without sending the request
     */
    async countRequestOpts(requestParameters: CountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['waitlistId'] == null) {
            throw new runtime.RequiredError(
                'waitlistId',
                'Required parameter "waitlistId" was null or undefined when calling count().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list/{waitlistId}/user/count`;
        urlPath = urlPath.replace(`{${"waitlistId"}}`, encodeURIComponent(String(requestParameters['waitlistId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns total user count and referred user count for a waitlist.
     * Get waitlist user counts
     */
    async countRaw(requestParameters: CountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WaitListUserCountResponseDto>> {
        const requestOptions = await this.countRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WaitListUserCountResponseDtoFromJSON(jsonValue));
    }

    /**
     * Returns total user count and referred user count for a waitlist.
     * Get waitlist user counts
     */
    async count(requestParameters: CountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WaitListUserCountResponseDto> {
        const response = await this.countRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for findByEmail without sending the request
     */
    async findByEmailRequestOpts(requestParameters: FindByEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['waitlistId'] == null) {
            throw new runtime.RequiredError(
                'waitlistId',
                'Required parameter "waitlistId" was null or undefined when calling findByEmail().'
            );
        }

        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling findByEmail().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list/{waitlistId}/user/search`;
        urlPath = urlPath.replace(`{${"waitlistId"}}`, encodeURIComponent(String(requestParameters['waitlistId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Finds a specific user in the waitlist by their email address.
     * Search user by email
     */
    async findByEmailRaw(requestParameters: FindByEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WaitListUserResponseDto>> {
        const requestOptions = await this.findByEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WaitListUserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Finds a specific user in the waitlist by their email address.
     * Search user by email
     */
    async findByEmail(requestParameters: FindByEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WaitListUserResponseDto> {
        const response = await this.findByEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for waitListUsersFindAll without sending the request
     */
    async waitListUsersFindAllRequestOpts(requestParameters: WaitListUsersFindAllRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['waitlistId'] == null) {
            throw new runtime.RequiredError(
                'waitlistId',
                'Required parameter "waitlistId" was null or undefined when calling waitListUsersFindAll().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list/{waitlistId}/user`;
        urlPath = urlPath.replace(`{${"waitlistId"}}`, encodeURIComponent(String(requestParameters['waitlistId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves all users registered in a specific waitlist. Requires owner authentication.
     * Get all waitlist users
     */
    async waitListUsersFindAllRaw(requestParameters: WaitListUsersFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WaitListUserResponseDto>>> {
        const requestOptions = await this.waitListUsersFindAllRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WaitListUserResponseDtoFromJSON));
    }

    /**
     * Retrieves all users registered in a specific waitlist. Requires owner authentication.
     * Get all waitlist users
     */
    async waitListUsersFindAll(requestParameters: WaitListUsersFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WaitListUserResponseDto>> {
        const response = await this.waitListUsersFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for waitListUsersRegister without sending the request
     */
    async waitListUsersRegisterRequestOpts(requestParameters: WaitListUsersRegisterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['waitlistId'] == null) {
            throw new runtime.RequiredError(
                'waitlistId',
                'Required parameter "waitlistId" was null or undefined when calling waitListUsersRegister().'
            );
        }

        if (requestParameters['registerWaitListUserDto'] == null) {
            throw new runtime.RequiredError(
                'registerWaitListUserDto',
                'Required parameter "registerWaitListUserDto" was null or undefined when calling waitListUsersRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/wait-list/{waitlistId}/user`;
        urlPath = urlPath.replace(`{${"waitlistId"}}`, encodeURIComponent(String(requestParameters['waitlistId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterWaitListUserDtoToJSON(requestParameters['registerWaitListUserDto']),
        };
    }

    /**
     * Allows a user to register for a waitlist. This is a public endpoint that does not require authentication.
     * Register for a waitlist
     */
    async waitListUsersRegisterRaw(requestParameters: WaitListUsersRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WaitListUserResponseDto>> {
        const requestOptions = await this.waitListUsersRegisterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WaitListUserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Allows a user to register for a waitlist. This is a public endpoint that does not require authentication.
     * Register for a waitlist
     */
    async waitListUsersRegister(requestParameters: WaitListUsersRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WaitListUserResponseDto> {
        const response = await this.waitListUsersRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for waitListUsersRemove without sending the request
     */
    async waitListUsersRemoveRequestOpts(requestParameters: WaitListUsersRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['waitlistId'] == null) {
            throw new runtime.RequiredError(
                'waitlistId',
                'Required parameter "waitlistId" was null or undefined when calling waitListUsersRemove().'
            );
        }

        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling waitListUsersRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list/{waitlistId}/user/{email}`;
        urlPath = urlPath.replace(`{${"waitlistId"}}`, encodeURIComponent(String(requestParameters['waitlistId'])));
        urlPath = urlPath.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes a user from the waitlist by their email address.
     * Remove user from waitlist
     */
    async waitListUsersRemoveRaw(requestParameters: WaitListUsersRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.waitListUsersRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a user from the waitlist by their email address.
     * Remove user from waitlist
     */
    async waitListUsersRemove(requestParameters: WaitListUsersRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.waitListUsersRemoveRaw(requestParameters, initOverrides);
    }

}
