/* tslint:disable */
/* eslint-disable */
/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWaitListDto,
  UpdateWaitListDto,
  WaitListResponseDto,
} from '../models/index';
import {
    CreateWaitListDtoFromJSON,
    CreateWaitListDtoToJSON,
    UpdateWaitListDtoFromJSON,
    UpdateWaitListDtoToJSON,
    WaitListResponseDtoFromJSON,
    WaitListResponseDtoToJSON,
} from '../models/index';

export interface WaitListCreateRequest {
    createWaitListDto: CreateWaitListDto;
}

export interface WaitListFindOneRequest {
    id: object;
}

export interface WaitListRemoveRequest {
    id: object;
}

export interface WaitListUpdateRequest {
    id: object;
    updateWaitListDto: UpdateWaitListDto;
}

export interface WaitlistStatsRequest {
    waitlistId: object;
}

/**
 * 
 */
export class WaitListApi extends runtime.BaseAPI {

    /**
     * Creates request options for waitListCreate without sending the request
     */
    async waitListCreateRequestOpts(requestParameters: WaitListCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWaitListDto'] == null) {
            throw new runtime.RequiredError(
                'createWaitListDto',
                'Required parameter "createWaitListDto" was null or undefined when calling waitListCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWaitListDtoToJSON(requestParameters['createWaitListDto']),
        };
    }

    /**
     * Creates a new waitlist for the authenticated user.
     * Create a new waitlist
     */
    async waitListCreateRaw(requestParameters: WaitListCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WaitListResponseDto>> {
        const requestOptions = await this.waitListCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WaitListResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates a new waitlist for the authenticated user.
     * Create a new waitlist
     */
    async waitListCreate(requestParameters: WaitListCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WaitListResponseDto> {
        const response = await this.waitListCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for waitListFindAll without sending the request
     */
    async waitListFindAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves all waitlists owned by the authenticated user.
     * Get all waitlists
     */
    async waitListFindAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WaitListResponseDto>>> {
        const requestOptions = await this.waitListFindAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WaitListResponseDtoFromJSON));
    }

    /**
     * Retrieves all waitlists owned by the authenticated user.
     * Get all waitlists
     */
    async waitListFindAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WaitListResponseDto>> {
        const response = await this.waitListFindAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for waitListFindOne without sending the request
     */
    async waitListFindOneRequestOpts(requestParameters: WaitListFindOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling waitListFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a specific waitlist by ID.
     * Get a specific waitlist
     */
    async waitListFindOneRaw(requestParameters: WaitListFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WaitListResponseDto>> {
        const requestOptions = await this.waitListFindOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WaitListResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves a specific waitlist by ID.
     * Get a specific waitlist
     */
    async waitListFindOne(requestParameters: WaitListFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WaitListResponseDto> {
        const response = await this.waitListFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for waitListRemove without sending the request
     */
    async waitListRemoveRequestOpts(requestParameters: WaitListRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling waitListRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permanently deletes a waitlist. This action cannot be undone.
     * Delete a waitlist
     */
    async waitListRemoveRaw(requestParameters: WaitListRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.waitListRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes a waitlist. This action cannot be undone.
     * Delete a waitlist
     */
    async waitListRemove(requestParameters: WaitListRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.waitListRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for waitListUpdate without sending the request
     */
    async waitListUpdateRequestOpts(requestParameters: WaitListUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling waitListUpdate().'
            );
        }

        if (requestParameters['updateWaitListDto'] == null) {
            throw new runtime.RequiredError(
                'updateWaitListDto',
                'Required parameter "updateWaitListDto" was null or undefined when calling waitListUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWaitListDtoToJSON(requestParameters['updateWaitListDto']),
        };
    }

    /**
     * Updates an existing waitlist. Only the owner can update.
     * Update a waitlist
     */
    async waitListUpdateRaw(requestParameters: WaitListUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WaitListResponseDto>> {
        const requestOptions = await this.waitListUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WaitListResponseDtoFromJSON(jsonValue));
    }

    /**
     * Updates an existing waitlist. Only the owner can update.
     * Update a waitlist
     */
    async waitListUpdate(requestParameters: WaitListUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WaitListResponseDto> {
        const response = await this.waitListUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for waitlistStats without sending the request
     */
    async waitlistStatsRequestOpts(requestParameters: WaitlistStatsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['waitlistId'] == null) {
            throw new runtime.RequiredError(
                'waitlistId',
                'Required parameter "waitlistId" was null or undefined when calling waitlistStats().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT-auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/wait-list/{waitlistId}/stats`;
        urlPath = urlPath.replace(`{${"waitlistId"}}`, encodeURIComponent(String(requestParameters['waitlistId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves aggregated statistics for a specific waitlist owned by the authenticated user.
     * Get waitlist statistics
     */
    async waitlistStatsRaw(requestParameters: WaitlistStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.waitlistStatsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves aggregated statistics for a specific waitlist owned by the authenticated user.
     * Get waitlist statistics
     */
    async waitlistStats(requestParameters: WaitlistStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.waitlistStatsRaw(requestParameters, initOverrides);
    }

}
