/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WebhookConfigDto } from './webhookConfigDto';

export class CreateWaitListDto {
    /**
    * Name of the waitlist
    */
    'name': string;
    /**
    * Whether to send confirmation email to new signups
    */
    'sendEmailToNewSignup': boolean;
    /**
    * Webhook configuration for new signup notifications
    */
    'webhook'?: WebhookConfigDto;
    /**
    * Associated widget ID for embedding
    */
    'widgetId'?: string;
    /**
    * Whether the waitlist is accepting new signups
    */
    'isAvailable'?: boolean = true;
    /**
    * Whether the waitlist has security active
    */
    'isSecurityActive'?: boolean = false;
    /**
    * Email template ID to send to new signups
    */
    'emailTemplateToNewSignUps'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "sendEmailToNewSignup",
            "baseName": "sendEmailToNewSignup",
            "type": "boolean"
        },
        {
            "name": "webhook",
            "baseName": "webhook",
            "type": "WebhookConfigDto"
        },
        {
            "name": "widgetId",
            "baseName": "widget_id",
            "type": "string"
        },
        {
            "name": "isAvailable",
            "baseName": "isAvailable",
            "type": "boolean"
        },
        {
            "name": "isSecurityActive",
            "baseName": "isSecurityActive",
            "type": "boolean"
        },
        {
            "name": "emailTemplateToNewSignUps",
            "baseName": "emailTemplateToNewSignUps",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateWaitListDto.attributeTypeMap;
    }
}

