/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateCheckoutSessionDto {
    /**
    * Optional promotion code to apply immediately. If omitted, Stripe Checkout still allows entering a code manually.
    */
    'couponCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "couponCode",
            "baseName": "couponCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateCheckoutSessionDto.attributeTypeMap;
    }
}

