/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateUserDto {
    /**
    * User first name
    */
    'name': string;
    /**
    * User last name
    */
    'lastName': string;
    /**
    * User email address (must be unique)
    */
    'email': string;
    /**
    * User password
    */
    'password': string;
    /**
    * URL to user avatar image
    */
    'avatar'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateUserDto.attributeTypeMap;
    }
}

