/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReactToHtmlDto {
    /**
    * React component code to be compiled to HTML
    */
    'code': string;
    /**
    * Variables (props) to inject into the component at render time.
    */
    'variables'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "variables",
            "baseName": "variables",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return ReactToHtmlDto.attributeTypeMap;
    }
}

