/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RegisterWaitListUserDto {
    /**
    * Email address of the user joining the waitlist
    */
    'email': string;
    /**
    * Name of the user joining the waitlist
    */
    'name'?: string;
    /**
    * Referral code from another user who referred this signup
    */
    'referredBy'?: string;
    /**
    * Source channel of the signup (organic and referral are auto-determined)
    */
    'source'?: RegisterWaitListUserDto.SourceEnum;
    /**
    * Arbitrary key-value metadata to attach to the waitlist user
    */
    'metadata'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "referredBy",
            "baseName": "referredBy",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "RegisterWaitListUserDto.SourceEnum"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return RegisterWaitListUserDto.attributeTypeMap;
    }
}

export namespace RegisterWaitListUserDto {
    export enum SourceEnum {
        Social = <any> 'social',
        Email = <any> 'email',
        PaidAds = <any> 'paid_ads'
    }
}
