/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateWaitListUserStatusDto {
    /**
    * Email of the waitlist user
    */
    'email': string;
    /**
    * New status for the user
    */
    'status': UpdateWaitListUserStatusDto.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "UpdateWaitListUserStatusDto.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return UpdateWaitListUserStatusDto.attributeTypeMap;
    }
}

export namespace UpdateWaitListUserStatusDto {
    export enum StatusEnum {
        Waiting = <any> 'waiting',
        Invited = <any> 'invited',
        Converted = <any> 'converted',
        Churned = <any> 'churned'
    }
}
