/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WaitListResponseDto {
    /**
    * Unique identifier of the waitlist
    */
    'id': string;
    /**
    * Name of the waitlist
    */
    'name': string;
    /**
    * Whether confirmation emails are sent to new signups
    */
    'sendEmailToNewSignup': boolean;
    /**
    * Webhook URL for new signup notifications
    */
    'webhook'?: object;
    /**
    * Associated widget ID
    */
    'widgetId'?: string;
    /**
    * Whether the waitlist is accepting signups
    */
    'isAvailable': boolean;
    /**
    * Owner user ID
    */
    'userId': string;
    /**
    * Creation timestamp
    */
    'createdAt': Date;
    /**
    * Last update timestamp
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "sendEmailToNewSignup",
            "baseName": "sendEmailToNewSignup",
            "type": "boolean"
        },
        {
            "name": "webhook",
            "baseName": "webhook",
            "type": "object"
        },
        {
            "name": "widgetId",
            "baseName": "widget_id",
            "type": "string"
        },
        {
            "name": "isAvailable",
            "baseName": "isAvailable",
            "type": "boolean"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return WaitListResponseDto.attributeTypeMap;
    }
}

