/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WaitListUserCountResponseDto {
    /**
    * Total number of users in the waitlist
    */
    'total': number;
    /**
    * Number of users who signed up via referral
    */
    'referred': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "referred",
            "baseName": "referred",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WaitListUserCountResponseDto.attributeTypeMap;
    }
}

