/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WaitListUserResponseDto {
    /**
    * Unique identifier of the waitlist user entry
    */
    'id': string;
    /**
    * Email address of the registered user
    */
    'email': string;
    /**
    * Waitlist ID this user belongs to
    */
    'waitlistId': string;
    /**
    * Referral code of the user who referred this signup
    */
    'referredBy'?: string;
    /**
    * Unique referral code for this user to share
    */
    'referralCode': string;
    /**
    * Registration timestamp
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "waitlistId",
            "baseName": "waitlistId",
            "type": "string"
        },
        {
            "name": "referredBy",
            "baseName": "referredBy",
            "type": "string"
        },
        {
            "name": "referralCode",
            "baseName": "referral_code",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return WaitListUserResponseDto.attributeTypeMap;
    }
}

