/**
 * Zot API
 * #### Overview Zot API provides a comprehensive solution for managing waitlists and user authentication  #### Rate Limiting API requests are subject to rate limiting. Please handle 429 responses appropriately.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zot.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WebhookConfigDto {
    /**
    * Webhook URL to notify when a new user signs up
    */
    'url'?: string;
    /**
    * Notify webhook every N users registered
    */
    'range'?: number = 10;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "range",
            "baseName": "range",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WebhookConfigDto.attributeTypeMap;
    }
}

