services:
  # mongodb:
  #   container_name: mongodb_db
  #   image: mongo:latest

  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo_data:/data/db

  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: blaze
  #     MONGO_INITDB_ROOT_PASSWORD: blaze
    zot-api:
      build: .
      ports:
        - "3010:3010"
      env_file:
        - .env
      restart: unless-stopped

# volumes:
#   mongo_data:
#     driver: local
