import { ApiProperty } from "@nestjs/swagger";

export class CheckoutSessionResponseDto {
  @ApiProperty({
    description: "Checkout session id generated by Stripe",
    example: "cs_test_a1B2c3D4e5",
  })
  sessionId: string;

  @ApiProperty({
    description: "Stripe-hosted URL where the user completes the subscription purchase",
    example: "https://checkout.stripe.com/c/pay/cs_test_123",
  })
  url: string;
}

export class WebhookAcceptedResponseDto {
  @ApiProperty({
    description: "Indicates that webhook event was accepted",
    example: true,
  })
  received: boolean;
}
